### ISSUE TITLE
Issue with quantized/converted happzy2633/qwen2.5-7b-ins-v3

### ISSUE THREAD

**Issue by cchance27** [lmstudio-ai/mlx-engine#10]
https://huggingface.co/happzy2633/qwen2.5-7b-ins-v3

when i quantize and uploaded it it works with mlx-lm but when i use sideload to lm-studio ... it bombs out with an error during loading.

```
🥲 Failed to load the model

Failed to load model

Error when loading model: Exception: data did not match any variant of untagged enum ModelWrapper at line 757443 column 3
```

command used to quantize and upload....
python -m mlx_lm.convert --hf-path happzy2633/qwen2.5-7b-ins-v3 -q --upload-repo mlx-community/Happzy2633-Qwen2.5-7b-ins-v3-4bit

**Comment by neilmehta24** [comment]
Hello, thanks for the bug report. We found the issue, and it will be fixed in our next release.

**Comment by yagil** [comment]
Beta with the bug fix available here: https://lmstudio.ai/beta-releases

**Comment by cchance27** [comment]
That version works great thanks for the fix.
