### ISSUE TITLE
MLX models instantly crash after first message

### ISSUE THREAD

**Issue by beezbo** [lmstudio-ai/mlx-engine#11]
This is on MacOS with M1 Max 64GB on 0.3.4

![image](https://github.com/user-attachments/assets/665c4bdb-15d8-4813-b4da-e5b7e2502580)

**Comment by yagil** [comment]
@beezbo which macOS version are you on?

**Comment by yagil** [comment]
Likely due to macOS < 14, which is currently a requirement.
