### ISSUE TITLE
[Feature Request] Support for bitnet.cpp and BitNet models #89

### ISSUE THREAD

**Issue by dgallitelli** [lmstudio-ai/mlx-engine#15]
[bitnet.cpp](https://github.com/microsoft/BitNet) is the official inference framework for 1-bit LLMs (e.g., BitNet b1.58). It offers a suite of optimized kernels, that support fast and lossless inference of 1.58-bit models on CPU (with NPU and GPU support coming next).

It would be awesome for LMS to support bitnet.cpp and therefore BitNet models, for on-device evaluation.

**Comment by neilmehta24** [comment]
Hello, thanks for bringing this to our attention. We are aware of this feature request, and community discussion about this feature can be viewed here https://discord.com/channels/1110598183144399058/1297551194990051379/1297551194990051379 . Going to close this issue since it's not relevant to MLX.
