### ISSUE TITLE
Excessive RAM Usage in MLX on M1 Mac with Various Models

### ISSUE THREAD

**Issue by lucacri** [lmstudio-ai/mlx-engine#18]
Hello,

I am experiencing an issue with excessive RAM usage when using the MLX framework on my M1 Mac with 64GB of RAM. This problem seems to occur with any model I use, not just a specific one. For example, while working with the `qwen2.5-coder-7b-instruct` model, I observed the following:

**Environment:**

- **Device:** M1 Mac
- **RAM:** 64GB
- **Framework:** MLX
- **Example Model:** qwen2.5-coder-7b-instruct

**Steps to Reproduce:**

1. Load any model in the MLX environment, such as `qwen2.5-coder-7b-instruct`.
2. Monitor the RAM usage, which starts at a lower level (e.g., around 5GB).
3. Use the `aider` tool or perform usual operations.
4. Observe RAM usage increasing significantly over time, eventually reaching around 50GB (including utilization of swap memory).

**Expected Behavior:**

The RAM usage should remain within a reasonable expected range relative to the operations and size of the model being used, without ballooning uncontrollably.

**Actual Behavior:**

The RAM usage starts at a manageable level but increases substantially over time during use, eventually consuming nearly all available RAM and a significant portion of swap memory, affecting system performance.

**Additional Information:**

- This is not specific to any single model, as I have observed similar behavior with other models.
- The increase in RAM usage affects overall system performance and responsiveness.

Please let me know if there is any further information I can provide or if there are any potential solutions.

**Comment by neilmehta24** [comment]
`mlx_lm` and `mlx_vlm` have been updated to regularly clear the metal GPU cache. This issue will should be fixed in the next release of LM Studio

**Comment by lucacri** [comment]
Thank you! Any ETA on the next release?

**Comment by neilmehta24** [comment]
Check out the beta release version `0.3.5 build 8` here https://lmstudio.ai/beta-releases . Please re-open this issue if you see excessive RAM usage.
