### ISSUE TITLE
MLX you're using in release LM Studio seems to be outdated and broken for Q8 and larger models

### ISSUE THREAD

**Issue by orcinus** [lmstudio-ai/mlx-engine#34]
See thread here:
https://github.com/ml-explore/mlx-examples/issues/776

Large Q8 models like Qwen-VL-72B are uselessly slow unless loaded immediately after a fresh boot, even though there is plenty of RAM available (192GB Mac Studio). GPU usage is near 0% and they end up being executed pretty much entirely on CPU.

New MLX supposedly remedies this.

**Comment by neilmehta24** [comment]
The next version of our app should help remedy this, since we'll be shipping the latest version of MLX. See here https://github.com/ml-explore/mlx-examples/tree/main/llms#large-models for guidance from the MLX team about using large models.

**Comment by orcinus** [comment]
@neilmehta24 Thanks. The guidance is incomplete and solves nothing.
The correct kernel tweaks to make these work are actually:

```
sudo sysctl iogpu.disable_wired_collector=1
sudo sysctl iogpu.wired_limit_mb=n
```

Without the disable_wired_collector setting, the problem remains.
To make these persistent across reboots:

https://discussions.apple.com/thread/253840320?sortBy=rank
