### ISSUE TITLE
Feature Request: Add support for Pixtral and other Vision models (llama 3.2 11b/90b etc)

### ISSUE THREAD

**Issue by YorkieDev** [lmstudio-ai/mlx-engine#5]
Pixtral works great in mlx-vlm (https://github.com/Blaizzy/mlx-vlm/pull/67) would be great to see support land in LM Studio.

**Comment by youcefs21** [comment]
MLX version in lm studio is 0.0.13, pixtral is supported in 0.0.15, don't we just need to upgrade the MLX version?

**Comment by julien-blanchon** [comment]
Awesome v0.1.0 is now merged

**Comment by mattjcly** [comment]
Pixtral is now supported thanks to @Blaizzy !

**Comment by julien-blanchon** [comment]
I hope this will get bundled to LM Studio soon

**Comment by yagil** [comment]
> I hope this will get bundled to LM Studio soon

Not there yet, but keep an eye on https://lmstudio.ai/beta-releases

**Comment by neilmehta24** [comment]
As of #22, `mlx-engine` has Pixtral and Llama 3.2 vision support. We expect to roll this out to LM Studio soon.

**Comment by orcinus** [comment]
Any updates? Vision support in general in LM Studio is abysmal (UI and UX seem more like an MVP than actual usable thing). Combined with being months late with support for major vision-enabled LLMs makes using LM Studio a tough sell (and yes, i know it's free - i'd gladly pay for it if it meant faster rollout of features and architecture support).

**Comment by YorkieDev** [comment]
Marking this issue as solved as 0.3.5 Build 9 has support for Pixtral and Llama 3.2 Vision in the MLX Engine. 


https://lmstudio.ai/beta-releases

**Comment by orcinus** [comment]
Still doesn't work.
Getting `Unknown ArrayValue filter: trim` when trying to load MLX Llama 3.2 Vision Instruct.

**Comment by orcinus** [comment]
Nevermind, i'm dumb. Apparently, vision llama 3.2 does not have a System role (but regular 3.2 does). Weird.

**Comment by orcinus** [comment]
Unfortunately, it still doesn't work. It leaks RAM badly.
Deleting messages from context doesn't reduce RAM usage either, it just keeps ballooning the moment you start first inference.

**Comment by yagil** [comment]
@orcinus worth it to open an issue for performance. We'd track it separately. Also cc @Blaizzy

**Comment by orcinus** [comment]
I'm too slow - someone already did in here: https://github.com/lmstudio-ai/mlx-engine/issues/63
I've added my own case in that one.

**Comment by Blaizzy** [comment]
Thanks! 

I'm working on it from tomorrow.

**Comment by cleverestx** [comment]
Will this ever be completed? Just asking, thanks...
