### ISSUE TITLE
Please update build-in MLX engine to 0.21

### ISSUE THREAD

**Issue by dengcb** [lmstudio-ai/mlx-engine#54]
I want to load a 3-bit quantized MLX model, but only 0.21 mlx can support it.

Please tell me when can LM studio update to 0.21 mlx, thanks.

**Comment by YorkieDev** [comment]
@dengcb mlx v0.21 is in 0.3.5(build 8): https://lmstudio.ai/beta-releases

**Comment by dengcb** [comment]
> @dengcb mlx v0.21 is in 0.3.5(build 8): https://lmstudio.ai/beta-releases

Thanks, I'll try it.
