### ISSUE TITLE
Fix degraded performance of Qwen models

### ISSUE THREAD

**Issue by neilmehta24** [lmstudio-ai/mlx-engine#55]
Users of LM Studio are reporting that models such as `lmstudio-community/Qwen2.5-Coder-32B-Instruct-MLX-4bit` are generating slower after `mlx-engine` was upgraded to the latest deps.

**Comment by sonofsky2010** [comment]
After I update version to  build 9, the memory leak issues still happened. After six hours used the memory usage is up to 20GB. My model is qwen2.5-coder-3b-mlx which the memory usage was 1.5 GB when first load.

**Comment by neilmehta24** [comment]
> After I update version to build 9, the memory leak issues still happened. After six hours used the memory usage is up to 20GB. My model is qwen2.5-coder-3b-mlx-4b which the memory usage was 2 GB when first load.

Hello, thanks for reporting this. After long usage of the model, if you start a new chat and prompt the LLM, do you see the memory usage drop?

Is there a build version of LM Studio that doesn't have this issue?
