### ISSUE TITLE
Get error when trying to run self-quantized versions of Hermes-3-Llama-3.1-8B with 8-Bits and group-size 128

### ISSUE THREAD

**Issue by joseph777111** [lmstudio-ai/mlx-engine#6]
**System**
Mac OS Sequoia Version 15.0.1 (24A348)
2020 M1 MacBook Pro 16GB
```
uname -a: Darwin  24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:26 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8103 arm64
```

```
transformers       4.45.2
```

**Quantization Command**
```
python -m mlx_lm.convert --hf-path "$model" --quantize --q-group-size 128 --q-bits 8 --mlx-path ~/opt/Workspace/MLX/Hermes-3-Llama-3.1-8B-8Bit
```

After converting and quantizing NousResearch's Hermes-3-Llama-3.1-8B to 8Bits with groupsize 128, I get the following error when attempting to run the quantized model.

However, if I download and run a similar/identical MLX quantized version of the model from MLX Community's HuggingFace repo, it doesn't illicit any error. And, it runs fine. 🤔 

**Error Message Generated**
```
Error when loading model: Exception: data did not match any variant of untagged enum ModelWrapper at line 1251003 column 3
```

I ran the following test to make sure that the model I quantized works outside of LM Studio's mlx engine. These are the results:

```
python -m mlx_lm.generate --model  /Users/jsarnecki/opt/Models/MLX/Joseph717171/Hermes-3-Llama-3.1-8B-8Bit --prompt "hello"

==========
Prompt: <|begin_of_text|><|im_start|>user
hello<|im_end|>
<|im_start|>assistant

Hello! How can I assist you today? If you have any questions or need information on a particular topic, feel free to ask. I'll do my best to provide helpful and accurate responses.
==========
Prompt: 11 tokens, 6.502 tokens-per-sec
Generation: 40 tokens, 7.242 tokens-per-sec
Peak memory: 7.984 GB

```

The self-quantized model works with mlx_lm.generate, so my question is: why does LM Studio's MLX engine not work with the quantized models?

**Comment by neilmehta24** [comment]
Hello, thanks for the report. We believe this issue will be fixed in our next release.

**Comment by yagil** [comment]
@joseph777111 beta with the bug fix available here: https://lmstudio.ai/beta-releases

**Comment by joseph777111** [comment]
@yagil  Thanks, my dude!
