### ISSUE TITLE
A local quant doesn't use the GPU with LMStudio(0.3.5) and MLX_Amphibian(0.0.14 but does with mlx_lm.server(0.20.4)

### ISSUE THREAD

**Issue by coughmedicine2020** [lmstudio-ai/mlx-engine#62]
I converted EVA-UNIT-01/EVA-LLaMA-3.33-70B-v0.1 to 8bits locally using mlx_lm, I don't have the command line(sorry), and ran it using GPU via mlx_lm.server but LMS will only run it on the CPU.  I have 160GB set to unified memory.

I have a 13B model in 8bit I converted at the same time that runs on the GPU in both LMS and mlx_lm.server.  I haven't tried a hf.co model that is the same size but a different base model.

**Comment by neilmehta24** [comment]
Hello, thanks for reporting this. Can you please check if you have the same issue in the latest LM Studio beta `0.3.5 build 9`? https://lmstudio.ai/beta-releases

**Comment by coughmedicine2020** [comment]
Thanks, 0.3.5b9 correctly sees the self quant as 8bit and is using the GPU to process the 70b-8bit model, but fails to process the 13B-8bit model that release version worked fine with. The error the UI gives me is:
"Unsupported safetensors format: pt"

**Comment by neilmehta24** [comment]
@coughmedicine2020 `"Unsupported safetensors format: pt"` means that the model is in pytorch format and not in MLX format. Please ensure sure you are using the converted model and not the original model.

**Comment by coughmedicine2020** [comment]
I checked the sha256 fingerprints and I was trying to load the original files. Thanks.  AFAIK 0.3.5b9 solves the problem with my local quants. Thanks!
